@backendUrl=http://127.0.0.1:8000

### Get Home
GET {{backendUrl}}/ HTTP/1.1
Accept: application/json

### Get Backend Healthz
GET {{backendUrl}}/healthz HTTP/1.1
Accept: application/json

### Register User
POST {{backendUrl}}/users/register HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "username": "userOne",
  "email": "userOne@gmail.com",
  "password": "Ink@Hive"
}

### Login User
# @name userLogin
POST {{backendUrl}}/users/login HTTP/1.1
Accept: application/json
Content-Type: application/x-www-form-urlencoded

username=Test 2&password=Ink@Hive

### Get User login token
@authToken={{userLogin.response.body.access_token}}

### Create Post
POST {{backendUrl}}/posts/ HTTP/1.1
Authorization: Bearer {{authToken}}
Accept: application/json
Content-Type: application/json

{
  "title": "My Second Post",
  "content": "This is the content of my second post.",
  "category_id": 2
}

### List Posts
GET {{backendUrl}}/posts/ HTTP/1.1
Accept: application/json

### Get Post
GET {{backendUrl}}/posts/1 HTTP/1.1
Accept: application/json

### Update Post
PUT {{backendUrl}}/posts/1 HTTP/1.1
Authorization: Bearer {{authToken}}
Accept: application/json
Content-Type: application/json

{
  "title": "Updated Post Title",
  "content": "Updated content of the post."
}

### Delete Post
DELETE {{backendUrl}}/posts/1 HTTP/1.1
Accept: application/json

### List Categories
GET {{backendUrl}}/categories HTTP/1.1
Accept: application/json

### Get Category details
GET {{backendUrl}}/categories/2 HTTP/1.1
Accept: application/json

### Create Category
POST {{backendUrl}}/categories/ HTTP/1.1
Authorization: Bearer {{authToken}}
Accept: application/json
Content-Type: application/json

{
  "name": "Test"
}

### Update Category
PUT {{backendUrl}}/categories/1 HTTP/1.1
Authorization: Bearer {{authToken}}
Accept: application/json
Content-Type: application/json

{
  "name": "Updated Category Name"
}

### Delete Category
DELETE {{backendUrl}}/categories/1 HTTP/1.1
Accept: application/json
